version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - composer install --no-dev --optimize-autoloader
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
